# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='design',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='usability',
            field=models.IntegerField(),
        ),
    ]
